# pnpm Workspace Configuration
# pnpm モノレポ環境での依存関係管理とビルド最適化設定

# ====================================
# ワークスペース構成設定
# ====================================
packages:
  # メインアプリケーション（現在のディレクトリ）
  - "."

  # 将来のモノレポ拡張用（必要に応じてコメントアウト解除）
  # - 'packages/*'          # 個別パッケージ
  # - 'apps/*'              # 複数アプリケーション
  # - 'libs/*'              # 共有ライブラリ
  # - 'tools/*'             # 開発ツール

# ====================================
# ネイティブ依存関係の最適化設定
# ====================================
# バイナリ形式で配布される依存関係をソースからビルドする設定
# パフォーマンス向上と環境依存問題の解決に使用
onlyBuiltDependencies:
  # SWC（Speedy Web Compiler）
  # - Rust製の高速JavaScriptコンパイラ
  # - Babel/TypeScriptの代替として使用
  # - Viteプラグインで使用される
  - "@swc/core"

  # ESBuild
  # - Go製の超高速バンドラー/ミニファイヤー
  # - Viteの内部で使用される
  # - 開発時のHMRとプロダクションビルドで活用
  - "esbuild"

# ====================================
# 共有設定（オプション）
# ====================================
# すべてのワークスペースで共通の設定を定義
catalog:
  # React関連の共通バージョン管理（将来的に使用可能）
  # react: ^18.3.0
  # react-dom: ^18.3.0
  # typescript: ^5.0.0
# ====================================
# pnpm設定の最適化
# ====================================
# .npmrcファイルでの設定推奨項目（参考）
# shamefully-hoist=true           # hoistingの有効化（互換性向上）
# strict-peer-dependencies=false  # peer dependencies の厳格チェック無効
# auto-install-peers=true         # peer dependencies の自動インストール
# prefer-workspace-packages=true  # ワークスペース内パッケージの優先使用
